import { Invoice, InvoiceStatus, Classification, TaxField } from './types';

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: '1001',
    nifIssuer: '501234567',
    nameIssuer: 'Restaurante O Manel',
    date: '2025-01-15',
    total: 45.50,
    totalVat: 5.85,
    atcud: 'AT2025-1001',
    status: InvoiceStatus.APPROVED,
    classification: Classification.PERSONAL,
    taxField: null,
    confidence: 0.98,
    aiJustification: 'Refeição em fim de semana, classificada como pessoal baseado no histórico.',
    itemsDescription: 'Almoço: Bacalhau à Brás, Vinho Verde',
    quarter: 'Q1_2025'
  },
  {
    id: '1002',
    nifIssuer: '509876543',
    nameIssuer: 'Staples Portugal',
    date: '2025-01-18',
    total: 120.00,
    totalVat: 27.60,
    atcud: 'AT2025-1002',
    status: InvoiceStatus.APPROVED,
    classification: Classification.ACTIVITY,
    taxField: TaxField.F23,
    confidence: 0.95,
    aiJustification: 'Material de escritório detectado. Fornecedor de material de escritório.',
    itemsDescription: 'Papel A4, Tinteiros, Canetas',
    quarter: 'Q1_2025'
  },
  {
    id: '1003',
    nifIssuer: '505555555',
    nameIssuer: 'Oficina Zé dos Pneus',
    date: '2025-01-20',
    total: 350.00,
    totalVat: 80.50,
    atcud: 'AT2025-1003',
    status: InvoiceStatus.REVIEW_REQUIRED,
    classification: Classification.PENDING,
    taxField: TaxField.F23,
    confidence: 0.45,
    aiJustification: 'Reparação viatura. NIF da viatura não corresponde à frota registada.',
    itemsDescription: 'Mudança Pneus, Alinhamento',
    quarter: 'Q1_2025'
  },
  {
    id: '1004',
    nifIssuer: '502223334',
    nameIssuer: 'Makro Cash & Carry',
    date: '2025-01-22',
    total: 890.15,
    totalVat: 110.20,
    atcud: 'AT2025-1004',
    status: InvoiceStatus.APPROVED,
    classification: Classification.ACTIVITY,
    taxField: TaxField.F21,
    confidence: 0.99,
    aiJustification: 'Compra grossista de bens alimentares para stock.',
    itemsDescription: 'Bebidas diversas, Enlatados, Arroz',
    quarter: 'Q1_2025'
  },
  {
    id: '1005',
    nifIssuer: '501112223',
    nameIssuer: 'Worten Equipamentos',
    date: '2025-01-25',
    total: 1299.00,
    totalVat: 298.77,
    atcud: 'AT2025-1005',
    status: InvoiceStatus.PENDING,
    classification: Classification.ACTIVITY,
    taxField: TaxField.F24,
    confidence: 0.85,
    aiJustification: 'Equipamento informático de valor elevado. Sugere imobilizado.',
    itemsDescription: 'MacBook Air M2',
    quarter: 'Q1_2025'
  },
  {
    id: '1006',
    nifIssuer: '503334445',
    nameIssuer: 'Galp Energia',
    date: '2025-01-28',
    total: 85.00,
    totalVat: 19.55,
    atcud: 'AT2025-1006',
    status: InvoiceStatus.APPROVED,
    classification: Classification.ACTIVITY,
    taxField: TaxField.F23,
    confidence: 0.92,
    aiJustification: 'Combustível gasóleo. Dedução 50% assumida nas regras.',
    itemsDescription: 'Gasóleo Simples 50L',
    quarter: 'Q1_2025'
  },
  {
    id: '1007',
    nifIssuer: '506667778',
    nameIssuer: 'Continente Modelo',
    date: '2025-02-02',
    total: 215.40,
    totalVat: 18.50,
    atcud: 'AT2025-1007',
    status: InvoiceStatus.REVIEW_REQUIRED,
    classification: Classification.MIXED,
    taxField: null,
    confidence: 0.60,
    aiJustification: 'Mistura de artigos de limpeza (actividade) e artigos pessoais.',
    itemsDescription: 'Detergentes, Brinquedos, Ração cão',
    quarter: 'Q1_2025'
  }
];